Repository usommerl/graalnative4s, pull requests merged in 2021-02, with the labels that each got.

#62 Update tapir-core, tapir-http4s-server, ... to 0.17.9
  build.sbt
Labels: dependency-update

#63 Update http4s-blaze-server, http4s-circe, ... to 0.21.18
  build.sbt
Labels: dependency-update

#64 Update sbt-docker to 1.8.2
  project/plugins.sbt
Labels: dependency-update

#66 Update tapir-core, tapir-http4s-server, ... to 0.17.10
  build.sbt
Labels: dependency-update

#67 Update http4s-blaze-server, http4s-circe, ... to 0.21.19
  build.sbt
Labels: dependency-update

#65 Update odin-core, odin-slf4j to 0.11.0
  build.sbt
Labels: dependency-update

#68 Update tapir-core, tapir-http4s-server, ... to 0.17.11
  build.sbt
Labels: dependency-update

#69 Update munit to 0.7.22
  build.sbt
Labels: dependency-update

#70 Update tapir-core, tapir-http4s-server, ... to 0.17.12
  build.sbt
Labels: dependency-update

#71 Update munit-cats-effect-2 to 0.13.1
  build.sbt
Labels: dependency-update

#73 Add Java VM version to info endpoint
  build.sbt
  src/main/scala/server/Api.scala
  src/main/scala/server/Main.scala
  src/test/scala/ApiSpec.scala
Labels: enhancement

#74 Update scala to 2.13.4
  build.sbt
Labels: dependency-update

#75 Update GraalVM to 21.0.0.2
  Dockerfile
Labels: dependency-update

#76 Use dependabot to update the Dockerfile
  dependabot.yml
Labels: enhancement

#78 Replace pureconfig with ciris
  .github/workflows/cloud_run_env_vars
  README.md
  build.sbt
  src/main/resources/META-INF/native-image/native-image.properties
  src/main/resources/META-INF/native-image/resource-config.json
  src/main/resources/application.conf
  src/main/scala/server/Api.scala
  src/main/scala/server/Config.scala
  src/main/scala/server/Configuration.scala
  src/main/scala/server/Main.scala
  src/test/scala/ApiSpec.scala
Labels: enhancement

#79 Update tapir-core, tapir-http4s-server, ... to 0.17.13
  build.sbt
Labels: dependency-update

#81 Use refined to validate configuration values
  .github/workflows/cloud_run_env_vars
  build.sbt
  src/main/scala/server/Api.scala
  src/main/scala/server/Config.scala
  src/main/scala/server/Main.scala
  src/test/scala/ApiSpec.scala
Labels: enhancement

#82 Use release-drafter instead of GitHub changelog generator
  .github/release-drafter.yml
  .github/workflows/ci_cd.yaml
Labels: bug

#83 Update sbt-scalafix to 0.9.26
  project/plugins.sbt
Labels: dependency-update
